sudo: false

language: node_js

node_js:
  - '10'

cache:
  directories:
    - node_modules

script:
  - npm test

before_deploy:
  - npm run build

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    tags: true